[package]
name = "advent_of_code"
version = "0.10.0"
authors = [
    "Nick Davies <github@nicolasdavies.com.au>",
    "Felix Spöttel <1682504+fspoettel@users.noreply.github.com>"
]
edition = "2021"

[dependencies]
pico-args = "0.5.0"

[features]
test_lib = []
